### PR TITLE
Updated references to the deprecated ajaxify.variables object to the …

### PR DESCRIPTION
**Pull request by jongarrison**
Hi Nicolas!  Your plugin is great!  I've learned a lot by going through your code and I really like the way that you broke out and included your modules under /app.  I'm still new to node.js and I learned some good stuff from your code.  Anyway, when I installed your plugin on NodeBB 0.8.2, I ran into some errors related to the deprecated ajaxify.variables object.  I fixed two calls and then added a few minor things that would help somebody that was new to your plugin.

Thanks,
Jon

### CODE REVIEW

**Comment by NicolasSiver** [comment]
Yep, because plugin isn't compatible with 0.8 because of breaking changes.

`ajaxify.data.theirid` this is correct fix for 0.8 version of forum. I'll merge.
But you shouldn't bump version, It's part of publishing process ;)
Also because It's a breaking changes, major version will be bumped. I didn't provide update for 0.8 plugin because of this. I had plans to add some features, not just compatibility changes ;)

I'm not happy with current implementation of the plugin, so changes are incoming.

**Comment by jongarrison** [comment]
Thanks for the note on the version bump.  Good to know.

It's a great plugin, do you have notes on the other things you are adding?

**Comment by jongarrison** [comment]
I just added another commit to remove the version bump.  Good?

**Comment by NicolasSiver** [comment]
I would like concentrate on how plugin integrates in themes.
I will investigate this question a bit more. Solution will be based on new hooks and widgets areas.
There is a possibility that editing for custom fields will be at a separate page, like: `username/edit/custom-fields`.

> Good?
Good ;)

**Comment by jongarrison** [comment]
That sounds like a good addition.  It took me a little bit of poking around to realize that I had to manually add something to the profile template.  Not that bad, but it would be nice if there was a more automatic way.  Thanks again!

**Pull request merged**
